### Initiate Payment
POST {{url}}/payment/initiate
Content-Type: application/json

{
  "channel": "card",
  "amount": "5000",
  "email": "test@gmail.com",
  "pan": "6280511000000095",
  "pin": "1111",
  "cvv2": "111",
  "expireMonth": "04",
  "expireYear": "50"
}

### Authenticate OTP
POST {{url}}/payment/verify-otp
Content-Type: application/json

{
  "reference": "250619120WOIKYMJBCA",
  "otp": "123456"
}